### ISSUE TITLE
Support for ARM64 Apple Silicon

### ISSUE THREAD

**Issue by michalek-marcin** [needle-mirror/com.unity.xr.mock-hmd#1]
Hi,

I want to ask for adding support for Apple Silicon (arm64). Currently there is no option to run mock hmd on M1 MacBook Pro. There is only dll for intel platform.

![image](https://user-images.githubusercontent.com/54703654/207033830-d6597f1b-1ef8-44d6-9dfc-aeaf11965e7a.png)

**Comment by marwie** [comment]
Hello, this repository is not officially maintained by unity. Please repost your request in the unity forum or open a bug report to reach the devs there. Otherwise they will not see it unfortunately
